"""initial migration

Revision ID: 3a77186e702b
Revises: 
Create Date: 2026-04-06 00:09:38.776450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a77186e702b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('compliance_insights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('related_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_insights_created_at', 'compliance_insights', ['created_at'], unique=False)
    op.create_index('idx_insights_type', 'compliance_insights', ['type'], unique=False)
    op.create_table('mdf_projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('project_no', sa.String(length=100), nullable=False),
    sa.Column('classification', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mdf_projects_project_no'), 'mdf_projects', ['project_no'], unique=True)
    op.create_table('regulatory_requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('standard_name', sa.String(length=100), nullable=False),
    sa.Column('clause_no', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('requirement_text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_regulatory_standard_clause', 'regulatory_requirements', ['standard_name', 'clause_no'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('current_version', sa.String(length=20), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reserved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(doc_number, ''))", persisted=True), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_documents_created_at', 'documents', ['created_at'], unique=False)
    op.create_index('idx_documents_deleted_at', 'documents', ['deleted_at'], unique=False)
    op.create_index('idx_documents_keywords_gin', 'documents', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_search_vector_gin', 'documents', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_documents_status', 'documents', ['status'], unique=False)
    op.create_index(op.f('ix_documents_doc_number'), 'documents', ['doc_number'], unique=True)
    op.create_table('number_format',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=True),
    sa.Column('separator', sa.String(length=5), nullable=True),
    sa.Column('year_format', sa.String(length=4), nullable=True),
    sa.Column('sequence_digits', sa.Integer(), nullable=True),
    sa.Column('current_sequence', sa.Integer(), nullable=True),
    sa.Column('current_year', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('actor_name', sa.String(length=100), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_details_gin', 'audit_logs', ['details'], unique=False, postgresql_using='gin')
    op.create_index('idx_audit_details_version', 'audit_logs', [sa.text("(details->>'version')")], unique=False, postgresql_where=sa.text("details ? 'version'"))
    op.create_index('idx_audit_document_id', 'audit_logs', ['document_id'], unique=False)
    op.create_index('idx_audit_retention_expires', 'audit_logs', ['retention_expires_at'], unique=False, postgresql_where=sa.text('retention_expires_at IS NOT NULL'))
    op.create_table('document_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('ai_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ai_analysis_text', sa.Text(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version_number', name='uq_doc_version_number')
    )
    op.create_index('idx_versions_ai_metadata_gin', 'document_versions', ['ai_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_versions_document_id', 'document_versions', ['document_id'], unique=False)
    op.create_index('idx_versions_file_hash', 'document_versions', ['file_hash'], unique=False)
    op.create_table('mdf_document_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mdf_project_id', sa.UUID(), nullable=False),
    sa.Column('item_no', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['mdf_project_id'], ['mdf_projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_mdf_links_document_id', 'mdf_document_links', ['document_id'], unique=False)
    op.create_index('idx_mdf_links_project_id', 'mdf_document_links', ['mdf_project_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version_id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=3072), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['document_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chunks_document_id', 'document_chunks', ['document_id'], unique=False)
    op.create_index('idx_chunks_embedding_hnsw', 'document_chunks', [sa.text('(embedding::halfvec(3072)) halfvec_cosine_ops')], unique=False, postgresql_using='hnsw', postgresql_with={'m': 24, 'ef_construction': 200})
    op.create_index('idx_chunks_version_id', 'document_chunks', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chunks_version_id', table_name='document_chunks')
    op.drop_index('idx_chunks_embedding_hnsw', table_name='document_chunks', postgresql_using='hnsw', postgresql_with={'m': 24, 'ef_construction': 200})
    op.drop_index('idx_chunks_document_id', table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('idx_mdf_links_project_id', table_name='mdf_document_links')
    op.drop_index('idx_mdf_links_document_id', table_name='mdf_document_links')
    op.drop_table('mdf_document_links')
    op.drop_index('idx_versions_file_hash', table_name='document_versions')
    op.drop_index('idx_versions_document_id', table_name='document_versions')
    op.drop_index('idx_versions_ai_metadata_gin', table_name='document_versions', postgresql_using='gin')
    op.drop_table('document_versions')
    op.drop_index('idx_audit_retention_expires', table_name='audit_logs', postgresql_where=sa.text('retention_expires_at IS NOT NULL'))
    op.drop_index('idx_audit_document_id', table_name='audit_logs')
    op.drop_index('idx_audit_details_version', table_name='audit_logs', postgresql_where=sa.text("details ? 'version'"))
    op.drop_index('idx_audit_details_gin', table_name='audit_logs', postgresql_using='gin')
    op.drop_index('idx_audit_created_at', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('number_format')
    op.drop_index(op.f('ix_documents_doc_number'), table_name='documents')
    op.drop_index('idx_documents_status', table_name='documents')
    op.drop_index('idx_documents_search_vector_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_keywords_gin', table_name='documents', postgresql_using='gin')
    op.drop_index('idx_documents_deleted_at', table_name='documents')
    op.drop_index('idx_documents_created_at', table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_index('idx_regulatory_standard_clause', table_name='regulatory_requirements')
    op.drop_table('regulatory_requirements')
    op.drop_index(op.f('ix_mdf_projects_project_no'), table_name='mdf_projects')
    op.drop_table('mdf_projects')
    op.drop_index('idx_insights_type', table_name='compliance_insights')
    op.drop_index('idx_insights_created_at', table_name='compliance_insights')
    op.drop_table('compliance_insights')
    op.drop_table('categories')
    # ### end Alembic commands ###
