"""add ai processing status

Revision ID: 3ff6a27b715d
Revises: 3a77186e702b
Create Date: 2026-04-06 00:16:33.206430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ff6a27b715d'
down_revision: Union[str, None] = '3a77186e702b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('v_uq_exists')
    op.drop_table('v_rv_exists')
    op.drop_table('v_ret_exists')
    op.drop_index('idx_audit_details_file_name', table_name='audit_logs', postgresql_where="(details ? 'file_name'::text)")
    op.create_index('idx_audit_details_gin', 'audit_logs', ['details'], unique=False, postgresql_using='gin')
    op.drop_index('idx_chunks_embedding_ivfflat', table_name='document_chunks', postgresql_with={'lists': '5'}, postgresql_using='ivfflat')
    op.add_column('document_versions', sa.Column('ai_processing_status', sa.String(length=20), nullable=True))
    op.alter_column('document_versions', 'ai_metadata',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('idx_versions_deleted_at', table_name='document_versions')
    op.create_index('idx_versions_ai_metadata_gin', 'document_versions', ['ai_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_versions_file_hash', 'document_versions', ['file_hash'], unique=False)
    op.add_column('documents', sa.Column('ai_processing_status', sa.String(length=20), nullable=True))
    op.drop_index('idx_documents_paging', table_name='documents')
    op.create_index('idx_documents_keywords_gin', 'documents', ['keywords'], unique=False, postgresql_using='gin')
    op.add_column('number_format', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_unique_constraint(None, 'number_format', ['category_id'])
    op.create_foreign_key(None, 'number_format', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'number_format', type_='foreignkey')
    op.drop_constraint(None, 'number_format', type_='unique')
    op.drop_column('number_format', 'category_id')
    op.drop_index('idx_documents_keywords_gin', table_name='documents', postgresql_using='gin')
    op.create_index('idx_documents_paging', 'documents', [sa.text('created_at DESC'), sa.text('id DESC')], unique=False)
    op.drop_column('documents', 'ai_processing_status')
    op.drop_index('idx_versions_file_hash', table_name='document_versions')
    op.drop_index('idx_versions_ai_metadata_gin', table_name='document_versions', postgresql_using='gin')
    op.create_index('idx_versions_deleted_at', 'document_versions', ['deleted_at'], unique=False)
    op.alter_column('document_versions', 'ai_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('document_versions', 'ai_processing_status')
    op.create_index('idx_chunks_embedding_ivfflat', 'document_chunks', ['embedding'], unique=False, postgresql_with={'lists': '5'}, postgresql_using='ivfflat')
    op.drop_index('idx_audit_details_gin', table_name='audit_logs', postgresql_using='gin')
    op.create_index('idx_audit_details_file_name', 'audit_logs', [sa.text("(details ->> 'file_name'::text)")], unique=False, postgresql_where="(details ? 'file_name'::text)")
    op.create_table('v_ret_exists',
    sa.Column('exists', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('v_rv_exists',
    sa.Column('exists', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    op.create_table('v_uq_exists',
    sa.Column('exists', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
